### ISSUE TITLE
Beta / Live 7.0.3 - Empty

### ISSUE THREAD

**Issue by behub** [p3lim-wow/BonusRollPreview#18]
On Live and Beta and loot list is empty. It's empty in Mythic dungeons on live and beta. It's empty in raids as well.

![Demo](http://i.imgur.com/FR3MwuY.png)

On Beta all i run is ElvUI. On Live i run a bunch of other addons.

Clicking the arrow up and down does nothing to show the loot list.

**Comment by ShaunDreclin** [comment]
Can confirm I'm having the exact same issue, ran hfc mythic yesterday and none of the possible bonus loot was showing up. I dont use elvui so that's not related

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BonusRollPreview/commit/d46e4363e3acdce5f1aed3fc47383be494628008
https://github.com/p3lim-wow/BonusRollPreview/commit/a34f2f381acc7cc2493287009c933fa3e2d09d1f
https://github.com/p3lim-wow/BonusRollPreview/commit/2fb878c1206f19d34f008407001b39c8de156c2f
