### ISSUE TITLE
Add support for Arena/BG weekly bonus rolls

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/BonusRollPreview#22]
i got the item for 10 wins per week in arena and this showed up in chat.

**Comment by p3lim** [comment]
I don't do PvP so I'm not familiar with this part of the game.
Could you please explain in detail how this works? What item? Did you get a bonus roll window?

**Comment by bullsei** [comment]
You get a random item which's itemlevel is based on the highest rating you achieved the week before. I did get a bonus roll window.
You get the item when the match is over and the scoreboard shows up.

**Comment by p3lim** [comment]
Alright, thanks for the info. I'm going to add these events to the ignore list as it's _practically_ impossible to maintain a list for this.

**Comment by bullsei** [comment]
i see, i found this: PVP_WEEKLY_BONUS_DESCRIPTION, which is used in Blizzard_PVPUI.lua.
This string is filled up with information of the function GetWeeklyPVPRewardInfo(bracketIndex)
local completed, itemLevel, numWins, numWinsReq = GetWeeklyPVPRewardInfo(self.bracketIndex)

Maybe its possible to get the possible rewards using
C_PvP.GetArenaRewards(teamSize) or
C_PvP.GetRatedBGRewards()
But i am note sure what this functions are exactly returning
The API documentations says this:
 function C_PvP.GetArenaRewards(teamSize)
    Part of the PvpInfo system
    Arguments
       1. number teamSize
   Returns
       1. number honor
       2. number experience
       3. (optional) table of BattlefieldReward rewards
  
 structure BattlefieldReward
    Part of the PvpInfo system
    Fields
       number id
       string name
       number texture
       number quantity

So i could imagine that its possible to combine the returned itemlevel using GetWeeklyPVPRewardInfo(bracketIndex) with C_PvP.GetArenaRewards
but i am not sure, since the function C_PvP.GetArenaRewards doesn't return rewards while being in garrison 2.0.

**Comment by p3lim** [comment]
Until I (or someone else) can figure out how to get loot data these events are ignored with https://github.com/p3lim-wow/BonusRollPreview/commit/a857f4a0bbb112c9c302a54e0968484cdaec7cfa

**Comment by p3lim** [comment]
See #41.
