### ISSUE TITLE
Goroth bonus roll missing - version  70200.39-Release

### ISSUE THREAD

**Issue by ceylina** [p3lim-wow/BonusRollPreview#23]
[08:20:41] BonusRollPreview: Found an unknown spell [240655]. Please report this, with boss name!

**Comment by p3lim** [comment]
I play on EU, so I won't have the bosses added until the end of Wednesday.

**Comment by ceylina** [comment]
No rush, it's not a big issue at all. Just wanted to pass it along since it popped up last night. I'm sure all TOS bosses need adding.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BonusRollPreview/commit/87890e90351a5743323996cdd2393b0ab9673fcc
