### ISSUE TITLE
 70200.40-Release error leaving first wing lfr

### ISSUE THREAD

**Issue by ceylina** [p3lim-wow/BonusRollPreview#26]
1x BonusRollPreview\BonusRollPreview-70200.40-Release.lua:323: Usage: EJ_SetDifficulty(difficulty)
[C]: in function `EJ_SetDifficulty'
BonusRollPreview\BonusRollPreview-70200.40-Release.lua:323: in function `StartEncounter'
BonusRollPreview\BonusRollPreview-70200.40-Release.lua:438: in function `?'
BonusRollPreview\BonusRollPreview-70200.40-Release.lua:501: in function <BonusRollPreview\BonusRollPreview.lua:500>

Locals:
(*temporary) = nil

**Comment by p3lim** [comment]
I'll look into this later this week, thanks for reporting.

**Comment by p3lim** [comment]
Fixed with https://github.com/p3lim-wow/BonusRollPreview/commit/a6a300c736a4c481e9a89a08aae63b80103b53ed
