### ISSUE TITLE
BonusRoll on Argus LFR

### ISSUE THREAD

**Issue by yoshimo** [p3lim-wow/BonusRollPreview#27]
- What version are you using?                                 
 70200.41
- Can the issue be reproduced, and if so, how?
        Kill Kin'garoth, second boss of the third wing (Hoffnungsbruch in deDE)
- If there was an error message, please include it.   
Found an unknown spell (250604) please report it

**Comment by yoshimo** [comment]
Unconfirmed data from the WH Database:

http://ptr.wowhead.com/spell=250541/7-3-raid-antorus-bonus-roll-loot-boss-01 
Garothi Worldbreaker

http://ptr.wowhead.com/spell=250574/7-3-raid-antorus-bonus-roll-loot-boss-02
Felhounds of Sargeras

http://ptr.wowhead.com/spell=250575/7-3-raid-antorus-bonus-roll-loot-boss-03
Antoran High Command

http://ptr.wowhead.com/spell=250576/7-3-raid-antorus-bonus-roll-loot-boss-04
Portal Keeper Hasabel

http://ptr.wowhead.com/spell=250577/7-3-raid-antorus-bonus-roll-loot-boss-05
Eonar the Life-Binder

http://ptr.wowhead.com/spell=250578/7-3-raid-antorus-bonus-roll-loot-boss-06
Imonar the Soulhunter

http://ptr.wowhead.com/spell=250580/7-3-raid-antorus-bonus-roll-loot-boss-08
Varimathras

http://ptr.wowhead.com/spell=250581/7-3-raid-antorus-bonus-roll-loot-boss-09
The Coven of Shivarra

http://ptr.wowhead.com/spell=250582/7-3-raid-antorus-bonus-roll-loot-boss-10
Aggramar

http://ptr.wowhead.com/spell=250583/7-3-raid-antorus-bonus-roll-loot-boss-11
Argus the Unmaker

Not sure how to get the other numbers in the triplets

**Comment by p3lim** [comment]
I've been working on some reworking that doesn't require manually collecting IDs any more, so the version that will be out for 7.3 won't require a database update.
Thanks though!
