### ISSUE TITLE
Bonus Roll Frame cannot be moved with MoveAnything

### ISSUE THREAD

**Issue by dle0105** [p3lim-wow/BonusRollPreview#28]
- What version are you using? - **70200.42-Release**
- Can the issue be reproduced, and if so, how? - **Yes, just try moving the frame with MoveAnything**
- If there was an error message, please include it. - **N/A**
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here). - **N/A**

**Since the latest update I am unable to move the bonus roll frame with the addon MoveAnything. Enabling BonusRollPreview moves the frame to an undesired location and locks it. Disabling it puts it back to where I had it.**

**No errors.**

**Comment by p3lim** [comment]
Support for moving the frame was added to the add-on itself, `/brp lock`.

**Comment by dle0105** [comment]
Well, I sure feel like an idiot. When I read the changes I mistook the "move the bonusrollframe" as moving the list. Sorry!
