### ISSUE TITLE
Some items are not being filtered correctly resulting in "Retrieving item information" 

### ISSUE THREAD

**Issue by Ghli** [p3lim-wow/BonusRollPreview#29]
- What version are you using?
    **70300.43-Release**
- Can the issue be reproduced, and if so, how?
    **Repeatable via different toons on world bosses/raid bosses/etc**
- If there was an error message, please include it. 

```
3x BonusRollPreview\BonusRollPreview-70300.43-Release.lua:204: Bad Argument: EJ_GetLootInfoByIndex(index [, encounterIndex]): Invalid index.
[C]: in function `EJ_GetLootInfoByIndex'
BonusRollPreview\BonusRollPreview-70300.43-Release.lua:204: in function `UpdateItem'
BonusRollPreview\BonusRollPreview-70300.43-Release.lua:74: in function <BonusRollPreview\BonusRollPreview.lua:54>

Locals:
InCombatSkipped
```

- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).

![image](https://user-images.githubusercontent.com/1237358/30005039-b1e12454-908e-11e7-9dba-15d20044fd20.png)

**Comment by p3lim** [comment]
Please try out the latest alpha on Curse (specifically for https://github.com/p3lim-wow/BonusRollPreview/commit/81b258c9e324bb8b9b4a9a064773d32cadd0f332).

**Comment by p3lim** [comment]
I couldn't seem to get this error when testing with the 70300.43-Release, not sure what's causing this.

**Comment by Ghli** [comment]
It's sporadic on when .43-Release will cause it to show up. Si'vash did not cause this error on .43-Release-1-g81b258c-alpha while on a paladin. I'm checking on a druid in the next 5 minutes.

**Comment by Ghli** [comment]
No error popped up while on .43-Release-1-g81b258c-alpha while using the druid, a demon hunter, a monk, and a hunter. I'm currently unable to test any other classes at the moment.

**Comment by p3lim** [comment]
I'm pushing the release then, it's a temporary (wasteful) fix until I can test the actual cause myself.
Leaving this issue open until then, thanks for reporting!
