### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Galiwyx** [p3lim-wow/BonusRollPreview#30]
Hello,

Since the release of the 8.0.1, I have a lua error : 

`Message: Error loading Interface\AddOns\BonusRollPreview\libs\EJ_Ext\LibStub\LibStub.lua
Time: Wed Jul 18 13:15:07 2018
Count: 5`

thank you !

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BonusRollPreview/commit/3ea494e24ec4f1aefeb85494f151d700b8689428
