### ISSUE TITLE
Error report v46

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/BonusRollPreview#34]
This error popped up in Battle for Dazar'alor, I haven't had a chance to go back but I disabled the addon as I couldn't see loot in the dungeon journal either.

```3x BonusRollPreview\BonusRollPreview-80000.46-Release.lua:128: Bad Instance ID.  Usage: EJ_SelectInstance(ID)
[C]: in function `EJ_SelectInstance'
BonusRollPreview\BonusRollPreview-80000.46-Release.lua:128: in function `StartEncounter'
BonusRollPreview\BonusRollPreview-80000.46-Release.lua:98: in function <BonusRollPreview\BonusRollPreview.lua:54>

Locals:
InCombatSkipped```

**Comment by Cluuey** [comment]
I just noticed the following error in BugSack was the dungeon journal and thought that might help you.
I don't know if it will but more information is normally better than too little.
```2x ...zzard_EncounterJournal\Blizzard_EncounterJournal-1.0.lua:631: Bad Instance ID.  Usage: EJ_SelectInstance(ID)
[C]: in function `EJ_SelectInstance'
...zzard_EncounterJournal\Blizzard_EncounterJournal-1.0.lua:631: in function `EncounterJournal_DisplayInstance'
...zzard_EncounterJournal\Blizzard_EncounterJournal-1.0.lua:2286: in function `EncounterJournal_OpenJournal'
FrameXML\LootFrame.lua:852: in function <FrameXML\LootFrame.lua:834>

Locals:
(*temporary) = 0
```

**Comment by gixxpunk** [comment]
That's because the addon is missing the InstanceID of Dattle of Dazar'alor raid in this file:
 https://github.com/p3lim-wow/BonusRollPreview/blob/master/libs/EJ_Ext/EJ_Ext.lua

**Comment by p3lim** [comment]
Please try the latest version from GitHub, I don't raid any more so I can't test.

**Comment by Cluuey** [comment]
Will do.
I guess that will be some time tomorrow but I'm in Oz so much later than US players.

**Comment by Cluuey** [comment]
Sorry I haven't got back to you, I've been unwell.

I had meant to ask how to use the version from here as just downloading the zip file, extracting it and changing the folder name, didn't work.
It gave errors about missing the Wasabi library.

So I replaced the file gixxpunk mentioned above, but that didn't work either.

Then I got sick and hadn't looked into it further.
Looking now I'll grab the missing _libs_ directories from the previous version and see if it works.

**Comment by p3lim** [comment]
For this change, you only need to replace BonusRollPreview.lua with the one from GitHub.

**Comment by Cluuey** [comment]
I didn't get any errors the other night, so I'd say you've sorted this out.
Thanks. :-)

**Comment by p3lim** [comment]
👍

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BonusRollPreview/commit/03b5ad144dec2e74b9c96559757b82025831b3a1
