### ISSUE TITLE
attempt to index global 'BonusRollPreviewDB' (a nil value)

### ISSUE THREAD

**Issue by class2u** [p3lim-wow/BonusRollPreview#37]
- What version are you using?
80100.47-Release

- Can the issue be reproduced, and if so, how?
Delete BonusRollPreview.lua in SavedVariables folder and then start WoW.

The content of BonusRollPreview.lua in SavedVariables folder has only one line:
BonusRollPreviewDB = nil

- If there was an error message, please include it.

1x BonusRollPreview\BonusRollPreview-80100.47-Release.lua:121: attempt to index global 'BonusRollPreviewDB' (a nil value)
BonusRollPreview\BonusRollPreview-80100.47-Release.lua:121: in function <BonusRollPreview\BonusRollPreview.lua:54>

Locals:
self = BonusRollPreview {
 UpdateHandlePosition = <function> defined @BonusRollPreview\BonusRollPreview.lua:244
 buttons = <table> {
 }
 StartEncounter = <function> defined @BonusRollPreview\BonusRollPreview.lua:125
 OnLoad = <function> defined @BonusRollPreview\BonusRollPreview.lua:37
 RegisterSafeEvent = <function> defined @BonusRollPreview\BonusRollPreview.lua:225
 0 = <userdata>
 UpdateItemFilter = <function> defined @BonusRollPreview\BonusRollPreview.lua:215
 OnEvent = <function> defined @BonusRollPreview\BonusRollPreview.lua:54
 ToggleLock = <function> defined @BonusRollPreview\BonusRollPreview.lua:286
 UpdatePosition = <function> defined @BonusRollPreview\BonusRollPreview.lua:275
 UpdateItems = <function> defined @BonusRollPreview\BonusRollPreview.lua:133
 DisableScrolling = <function> defined @BonusRollPreview\BonusRollPreview.lua:305
 Toggle = <function> defined @BonusRollPreview\BonusRollPreview.lua:312
 EnableScrolling = <function> defined @BonusRollPreview\BonusRollPreview.lua:291
 UnregisterSafeEvent = <function> defined @BonusRollPreview\BonusRollPreview.lua:235
 ScrollFrame = <unnamed> {
 }
}
event = "PLAYER_LOGIN"
(*temporary) = <function> defined =[C]:-1
(*temporary) = BonusRollPreviewAnchor {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'BonusRollPreviewDB' (a nil value)"
tSize = <function> defined @BonusRollPreview\BonusRollPreview.lua:26
query = <table> {
}
LE_SPELL_CONFIRMATION_PROMPT_TYPE_BONUS_ROLL = 1
ignoredSpells = <table> {
 240052 = true
 240042 = true
 232109 = true
 240048 = true
}
EJ = <table> {
 GetJournalInfoForSpellConfirmation = <function> defined @BonusRollPreview\libs\EJ_Ext\EJ_Ext.lua:183
}

**Comment by p3lim** [comment]
Thanks, I'll take a look at it.

**Comment by p3lim** [comment]
Can't seem to replicate this issue, so let's narrow it down.

1. How did you install this addon? (and from where)
2. Have you set to un-embed libraries?
   - Check if Wasabi is present within the `libs` subdirectory of BonusRollPreview.

**Comment by class2u** [comment]
I reinstalled and it works fine now.

I just found out that this is my fault. I try to localize the name of option panel via adding code in Options.lua cause this error:
Options.name = L['BonusRollPreview']

Thank you for your attention and sorry for this.
