### ISSUE TITLE
9.01 Shadowlands Error SetBackdrop

### ISSUE THREAD

**Issue by yoshimo** [p3lim-wow/BonusRollPreview#40]
Count: 1
Message: ...terface\AddOns\BonusRollPreview\BonusRollPreview.lua line 42:
   attempt to call method 'SetBackdropColor' (a nil value)
Debug:
   [string "@BonusRollPreview\BonusRollPreview.lua"]:42:
      ...terface\AddOns\BonusRollPreview\BonusRollPreview.lua:37

**Comment by p3lim** [comment]
a80621f7839f185b65780fb6accfef174b62ce8c
